import type { Metadata } from "next";

export const rootMetadata: Metadata = {
  title: {
    default: "FayraShop",
    template: "%s | FayraShop - Fair Price, Fast Delivery, and Full Satisfaction",
  },
  description: "FayraShop is your trusted online store for quality, affordability, and reliability. We offer a wide range of authentic and verified products at fair prices. Enjoy fast delivery, easy returns, and friendly customer support with every order. Our mission is to make your shopping experience smooth, secure, and satisfying.",
  keywords: [
    "FayraShop",
    "FayraShop Online Store",
    "E-commerce",
    "Online Shopping",
    "Quality Products",
    "Affordable Prices",
    "Reliable Delivery",
    "Easy Returns",
    "Friendly Customer Support",
    "Secure Shopping",
    "Verified Products",
    "Wide Range",
    "Fast Delivery",
    "Customer Satisfaction",
    "Trusted Store",
    "Authentic Products",
    "Affordable Prices",
    "Reliable Delivery",
    "Easy Returns",
    "Friendly Customer Support",
    "Secure Shopping",
    "Verified Products",
    "Wide Range",
    "Fast Delivery",
    "Customer Satisfaction",
    "Trusted Store",
    "Authentic Products",
    "Affordable Prices",
    "Reliable Delivery",
    "Easy Returns",
    "Friendly Customer Support",
    "Secure Shopping",
    "Verified Products",
    "Wide Range",
    "Fast Delivery",
    "Customer Satisfaction",
    "Trusted Store",
    "Authentic Products",
    "Affordable Prices",
    "Reliable Delivery",
    "Easy Returns",
    "Friendly Customer Support",
    "Secure Shopping",
    "Verified Products",
    "Wide Range",
    "Fast Delivery",
    "Customer Satisfaction",
  ],
  authors: [{ name: "FayraShop" }],
  creator: "@FayraShop",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://fayrashop.com",
    title: "FayraShop - Fair Price, Fast Delivery, and Full Satisfaction",
    description: "FayraShop is your trusted online store for quality, affordability, and reliability. We offer a wide range of authentic and verified products at fair prices. Enjoy fast delivery, easy returns, and friendly customer support with every order. Our mission is to make your shopping experience smooth, secure, and satisfying.",
    siteName: "FayraShop - Fair Price, Fast Delivery, and Full Satisfaction",
  },
  twitter: {
    card: "summary_large_image",
    title: "FayraShop - Fair Price, Fast Delivery, and Full Satisfaction",
    description: "FayraShop is your trusted online store for quality, affordability, and reliability. We offer a wide range of authentic and verified products at fair prices. Enjoy fast delivery, easy returns, and friendly customer support with every order. Our mission is to make your shopping experience smooth, secure, and satisfying.",
    creator: "@fayrashop",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};
